name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 25

      - name: Install Linux deps
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot binutils

      - name: Build app
        run: ./gradlew shadowJar

      - name: Build Linux package
        run: ./build.sh linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: build/dest/linux/

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 25

      - name: Build app
        shell: bash
        run: ./gradlew shadowJar

      - name: Build Windows package
        shell: bash
        run: ./build.sh windows

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: build/dest/windows/

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 25

      - name: Build app
        run: ./gradlew shadowJar

      - name: Build macOS package
        run: ./build.sh mac

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-installer
          path: build/dest/mac/

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-installer
          path: dist/linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: dist/windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-installer
          path: dist/mac

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/linux/**/*
            dist/windows/**/*
            dist/mac/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}